version: "3"
services:

  zk:
    image: zookeeper:3.6.2
    hostname: zk
    environment:
      ZOO_ADMINSERVER_ENABLED: "false"
      ZOO_STANDALONE_ENABLED: "true"
      ZOO_MAX_CLIENT_CNXNS: "0"
    ports:
      - 2181:2181

  jn1:
    image: dcagatay/hadoop:latest
    # hostname: jn1
    env_file:
      - hadoop.env
    environment:
      HADOOP_ROLE: journalnode
    ports:
      - 8480:8480
      - 8485:8485
    # volumes:
    #   - ./data/jn1:/var/lib/hadoop

  jn2:
    image: dcagatay/hadoop:latest
    # hostname: jn2
    env_file:
      - hadoop.env
    environment:
      HADOOP_ROLE: journalnode
    ports:
      - 8481:8480
      - 8486:8485
    # volumes:
    #   - ./data/jn2:/var/lib/hadoop

  jn3:
    image: dcagatay/hadoop:latest
    # hostname: jn3
    env_file:
      - hadoop.env
    environment:
      HADOOP_ROLE: journalnode
    ports:
      - 8482:8480
      - 8487:8485
    # volumes:
    #   - ./data/jn3:/var/lib/hadoop

  nn1:
    build: ./
    image: dcagatay/hadoop:latest
    # hostname: nn1
    env_file:
      - hadoop.env
    environment:
      HADOOP_ROLE: namenode
      DFS_HA_NAMENODE_ID: nn1
    ports:
      - 8020:8020
      - 50070:50070
      - 8019:8019
    # volumes:
    #   - ./data/nn1:/var/lib/hadoop

  nn2:
    image: dcagatay/hadoop:latest
    # hostname: nn2
    env_file:
      - hadoop.env
    environment:
      HADOOP_ROLE: namenode
      DFS_HA_NAMENODE_ID: nn2
      STANDBY: "true"
    ports:
      - 8021:8020
      - 50071:50070
      - 8029:8019
    # volumes:
    #   - ./data/nn2:/var/lib/hadoop

  nn3:
    image: dcagatay/hadoop:latest
    # hostname: nn3
    env_file:
      - hadoop.env
    environment:
      HADOOP_ROLE: namenode
      DFS_HA_NAMENODE_ID: nn3
      STANDBY: "true"
    ports:
      - 8022:8020
      - 50072:50070
      - 8039:8019
    # volumes:
    #   - ./data/nn3:/var/lib/hadoop

  dn1:
    image: dcagatay/hadoop:latest
    # hostname: dn1
    env_file:
      - hadoop.env
    environment:
      HADOOP_ROLE: datanode
      DFS_DATANODE_HOSTNAME: "dn1"
    ports:
      - 9864:9864
      - 9866:9866
      - 9867:9867
    # volumes:
    #   - ./data/dn1:/var/lib/hadoop

  dn2:
    image: dcagatay/hadoop:latest
    # hostname: dn2
    env_file:
      - hadoop.env
    environment:
      HADOOP_ROLE: datanode
      DFS_DATANODE_HOSTNAME: "dn2"
    ports:
      - 9874:9864
      - 9876:9866
      - 9877:9867
    # volumes:
    #   - ./data/dn2:/var/lib/hadoop

  dn3:
    image: dcagatay/hadoop:latest
    # hostname: dn3
    env_file:
      - hadoop.env
    environment:
      HADOOP_ROLE: datanode
      DFS_DATANODE_HOSTNAME: "dn3"
    ports:
      - 9884:9864
      - 9886:9866
      - 9887:9867
    # volumes:
    #   - ./data/dn3:/var/lib/hadoop

